name: medlife_v2
description: MedLife Vendor App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  shared_preferences: ^2.2.0

dev_dependencies:
  lint: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
